run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    #- bodyclose
    - deadcode
    - depguard
    #- dogsled
    #- dupl
    - errcheck
    - errorlint
    #- exhaustive
    #- funlen
    - gas
    #- gochecknoinits
    - goconst
    #- gocritic
    #- gocyclo
    #- gofmt
    - goimports
    #- golint
    #- gomnd
    #- goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    #- interfacer
    #- lll
    #- maligned
    - megacheck
    #- misspell
    #- nakedret
    #- noctx
    - nolintlint
    #- revive
    #- rowserrcheck
    #- scopelint
    - staticcheck
    - structcheck
    #- stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    #- whitespace
  fast: false

linters-settings:
  gosimple:
    checks: ["all", "-S1028"]
  staticcheck:
    checks: ["all"]
  gosec:
    # To specify a set of rules to explicitly exclude.
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G306
